from enum import Enum

Keydef = Enum('Keydef', [
	# main
	'quit',
	'toggle_grid_mode',
	'preserve_viewport',
	'preload_thumbnail',
	# image mode
	'image_view_left',
	'image_view_right',
	'image_view_up',
	'image_view_down',
	'image_view_zoom_in',
	'image_view_zoom_out',
	'image_view_zoom_origin',
	'image_view_next',
	'image_view_prev',
	'image_view_first',
	'image_view_last',
	'image_view_zoom_fill',
	'image_view_cw',
	'image_view_ccw',
	'image_view_mirror_v',
	'image_view_mirror_h',
	'image_navi_reload',
	'image_movie_pause_toggle',
	'image_movie_frame_forward',
	'image_canvas_eraser',
	'image_canvas_pen',
	'image_canvas_undo',
	'image_canvas_clear',
	'image_chessboard',
	# grid mode
	'grid_view_left',
	'grid_view_right',
	'grid_view_up',
	'grid_view_down',
	'grid_view_zoom_in',
	'grid_view_zoom_out',
	'grid_view_zoom_origin',
	'grid_view_first',
	'grid_view_last',
	'grid_hol',
	'grid_eol',
	'grid_page_up',
	'grid_page_up_half',
	'grid_page_down',
	'grid_page_down_half',
])
